{% set name = "django-session-security" %}
{% set version = "2.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 752b70865706afca39a62650eacd5d1e03a2baba31d46b2e1b96ad60c30553f3

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django >=2.2

test:
  imports:
    - session_security
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/yourlabs/django-session-security
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Django app that provides a mechanism to logout inactive authenticated users.
  description: |
    This app provides a mechanism to logout inactive authenticated users.
    An inactive browser should be logged out automatically if the user left
    his workstation, to protect sensitive data that may be displayed in the
    browser. It may be useful for CRMs, intranets, and such projects.
  doc_url: https://github.com/yourlabs/django-session-security
  dev_url: https://github.com/yourlabs/django-session-security

extra:
  recipe-maintainers:
    - swainn
